/* Kade's own hundred (Sep 20 2026). She pasted these as what a song idea should
 * look like: a genre tag, one very specific human situation, and often a craft
 * rule. "That generic shit is where you get fluorescent neon, shattered mirrors,
 * ghosts in the hallway, and somebody's heartbeat echoing through the universe
 * for the 400th time." The idea maker shows the writer a few of these at random
 * as the REGISTER to hit, never as material: a pitch that reuses one is thrown
 * away in code (see tooCloseToShelf in idea.ts). Her words, kept as she wrote
 * them. */
export const ideaShelf: string[] = [
  '90s-style R&B slow jam: Two people are lying awake after an argument, facing opposite directions in the same bed. Neither wants to apologize first. Write entirely from the tiny sounds and movements happening in that bedroom.',
  'Modern female R&B: A woman realizes the relationship is over because her partner stopped doing one tiny affectionate habit they\'ve done for years. Never say "we grew apart."',
  'Neo-soul: A late-night kitchen conversation between two people who almost dated ten years ago and are finally admitting they both knew.',
  'Quiet storm R&B: Someone keeps taking the long way home because they know an empty apartment is waiting.',
  'Sultry R&B: Attraction between two people who absolutely should not start anything, centered around the tension of sitting too close at a crowded gathering.',
  '2000s R&B: A woman deletes a man\'s number but still knows it from memory and hates that she does.',
  'Soul ballad: An older couple has the same dumb argument they\'ve had for forty years, but underneath it is deep familiarity and devotion.',
  'R&B duet: Both singers describe the same breakup dinner, but remember completely different versions of what happened.',
  'Alternative R&B: Someone recognizes an ex\'s shampoo smell on a stranger in a grocery aisle and gets thrown emotionally sideways for thirty seconds.',
  'R&B groove: A woman knows the guy she\'s seeing is bad news but loves how funny he is, and that is unfortunately enough to keep answering his calls.',
  'Boom-bap hip-hop: An adult walks through the neighborhood where they grew up and notices which things got demolished, renovated, or somehow never changed.',
  'Storytelling rap: A rapper narrates one ordinary Saturday in a small town where three unrelated lives quietly cross paths.',
  'Dark humorous rap: A broke person mentally calculates whether every minor inconvenience is financially survivable.',
  'Lyrical hip-hop: A song about people remembering completely different versions of you depending on which chapter of your life they knew.',
  'Conscious rap without preaching: Follow one twenty-dollar bill as it changes hands across a city for one day.',
  'Old-school rap: A rapper complains about technology through extremely specific modern annoyances while admitting half of it is convenient as hell.',
  'Southern hip-hop: A chaotic family cookout where everybody has history, somebody brought an unexpected boyfriend, and two relatives are pretending they aren\'t mad.',
  'Female rap: A woman calmly humiliates an arrogant man using observations instead of generic bragging or threats.',
  'Hip-hop storytelling: Two childhood friends meet again as adults after taking radically different paths, and the conversation is polite but strange.',
  'Rap concept song: Every verse is something the narrator nearly sent in a text but deleted.',
  '70s soul: A waitress working the closing shift watches the same lonely customer come in every Thursday and eventually learns why.',
  'Memphis soul: A man drives across town to apologize, rehearsing what he\'ll say at every red light, then loses his nerve when he arrives.',
  'Motown-inspired: Someone is genuinely trying to be happy for an ex getting married and doing a terrible job hiding the rest.',
  'Deep soul: A grown daughter discovers her father saved every birthday card she ever gave him.',
  'Southern soul: Two stubborn people keep finding excuses to visit each other after supposedly ending things.',
  'Vintage soul: A lover notices their partner always leaves the porch light on when they\'re angry but still expects them home.',
  'Soul waltz: Someone cleans out a deceased relative\'s junk drawer and learns more from the random contents than from any formal keepsake.',
  'Gritty soul: A factory worker sits in their car after a shift because ten quiet minutes alone feels luxurious.',
  'Soul duet: Two exes run into each other at a funeral and have to decide whether this is really the place to reopen old history.',
  'Piano soul ballad: Someone receives a voicemail from a loved one who died, years after forgetting it was saved.',
  'Traditional country: A woman inherits her grandmother\'s house and finds handwritten measurements, grocery lists, and phone numbers penciled inside cabinets.',
  '90s country: A divorced dad gets surprisingly emotional when his kid changes the preset radio stations in his truck.',
  'Outlaw country: A small-town troublemaker is getting older and slowly discovering everybody he used to party with now owns lawn equipment and talks about property taxes.',
  'Country story song: A waitress recognizes a former high-school bully sitting alone in her section twenty years later.',
  'Country duet: A couple argues about whether to sell the house where they raised their children after the kids have moved away.',
  'Country comedy: Someone\'s entire bad week is narrated through increasingly ridiculous things going wrong with their pickup, dog, phone, neighbor, and septic tank.',
  'Appalachian folk-country: A family keeps repeating the same sayings from a grandfather nobody younger than thirty actually remembers.',
  'Country soul: A woman discovers her dad secretly kept listening to the singer she introduced him to years ago.',
  'Blue-collar country: The narrator knows the exact noises their old house makes and can tell which floorboard means which family member is awake.',
  'Americana: A closed roadside motel becomes the central image for a town slowly being bypassed by newer highways.',
  'Delta blues: Someone owes money to half the town but still lends five dollars to somebody worse off.',
  'Electric blues: A man discovers his cheating partner because somebody keeps adjusting the driver\'s seat in his car.',
  'Acoustic blues: The narrator sits on the back steps during a summer storm arguing with nobody but themselves.',
  'Blues-rock: A mechanic knows everybody\'s secrets because people talk too freely while waiting for their cars.',
  'Slow blues: A bartender can tell which customers are newly heartbroken because they order differently.',
  'Chicago blues: Two old friends argue over who was actually responsible for a ridiculous incident decades ago.',
  'Swamp blues: Somebody goes fishing to avoid a difficult conversation and realizes the other person followed them.',
  'Blues shuffle: The narrator keeps lending tools to a neighbor who never returns a damn thing.',
  'Soul-blues: A woman knows her relationship is ending because Sunday mornings no longer feel comfortable.',
  'Dirty blues comedy: A flirtatious older narrator explains why maturity has not improved their taste in attractive disasters.',
  'Funk: Someone struts into a party pretending their life is together while hiding several increasingly absurd personal problems.',
  'Prince-style funk-rock: Sexual tension caused almost entirely by one person borrowing the other person\'s jacket and refusing to give it back.',
  '70s funk: A neighborhood barber narrates everybody\'s gossip while insisting he never gossips.',
  'Funk-pop: A woman becomes weirdly competitive over who can act less interested after a first date.',
  'P-Funk-inspired weirdness: An alien visits Earth and concludes human civilization revolves primarily around snacks, passwords, and pretending emails are important.',
  'Disco-funk: Someone goes dancing after a breakup intending to look devastated and accidentally has a fantastic night.',
  'Bass-heavy funk: A song entirely about the irrational confidence produced by wearing an outfit that fits perfectly.',
  'Funk-soul: A longtime couple flirts while doing completely mundane errands.',
  'Retro dance-funk: Somebody runs into their boss at a club and both silently agree Monday morning will involve selective amnesia.',
  'Funk comedy: A smooth-talking narrator keeps bragging while every verse accidentally reveals that they are kind of a mess.',
  'Grunge: Someone moves back into their childhood bedroom after their adult life falls apart and finds old stickers still stuck to the furniture.',
  'Alternative rock: Two siblings clean out their parents\' garage and start fighting over worthless objects with enormous emotional meaning.',
  '90s alt-rock: A person realizes they don\'t miss their ex; they miss the version of themselves who existed during that relationship.',
  'Garage rock: A disastrous first date becomes strangely charming because absolutely nothing goes according to plan.',
  'Post-grunge: Someone keeps an old answering machine because one message on it matters more than the machine does.',
  'Indie rock: A friend group slowly dissolves because everybody keeps saying "we should hang out sometime."',
  'Punk rock: An employee reaches the exact moment they stop caring about corporate motivational language.',
  'Pop-punk: Someone attends their high-school reunion expecting closure and mostly finds people complaining about lower-back pain.',
  'Southern rock: A family road trip becomes increasingly tense because everybody remembers the directions differently.',
  'Hard rock: A person finally confronts someone who constantly mistakes kindness for weakness, but the confrontation is conversational rather than superhero-posturing.',
  'Heavy metal: A song about being trapped inside a customer-service phone tree when you are already furious.',
  'Groove metal: Someone has spent years swallowing resentment and finally decides to say every specific thing they remember.',
  'Metalcore: A relationship argument where the brutal sections represent what the narrator wants to yell and the clean sections are what actually comes out.',
  'Nu metal: A narrator feels like everybody has a version of them they expect them to keep performing.',
  'Industrial metal: A warehouse night shift where machinery, fluorescent lights, exhaustion, and repetition become part of the rhythm.',
  'Doom metal: An elderly person quietly prepares their home for the possibility that they may not be living there much longer, without melodrama.',
  'Thrash metal: A song about bureaucratic paperwork escalating into irrational rage.',
  'Alternative metal/R&B hybrid: A soft sensual verse gradually turns into a furious confrontation when one small lie exposes a larger pattern.',
  'Gospel-metal fusion: Someone demands answers from God after a personal loss but refuses to stop talking to God.',
  'Metal with dark humor: The narrator treats assembling cheap furniture like an epic battle against an ancient enemy named Instruction Manual.',
  'Gospel-influenced soul: Someone who hasn\'t attended church in years catches themselves singing an old hymn while doing dishes.',
  'Secular gospel: A group of people gathers around a friend going through hell and refuses to let them disappear into themselves.',
  'Gospel-blues: A person argues with God in plain everyday language while driving home alone.',
  'Choir-driven soul: Different generations of one family each describe what "making it" means to them.',
  'Gospel funk: A joyous song about surviving a year that contained absolutely nothing glamorous.',
  'Piano gospel ballad: Someone admits they pray mostly when scared and wonders whether that still counts.',
  'Spiritual soul: A person feels unexpectedly connected to a deceased loved one while repeating one of their ordinary household routines.',
  'Gospel-country: A tiny rural congregation knows everyone\'s flaws and shows up for everyone anyway.',
  'Gospel R&B: Someone asks for enough strength to make one difficult phone call, not to fix their whole life.',
  'Gospel rap: A rapper talks about faith through doubts, petty failures, rent, family, exhaustion, humor, and ordinary survival instead of grand testimony cliches.',
  'Jazz/R&B: Two strangers flirt during repeated encounters at the same late-night diner but never exchange phone numbers.',
  'Trip-hop: Somebody listens through the apartment wall as their neighbors have the argument they wish they could have with their own partner.',
  'Psychedelic soul: Childhood memories surface out of order while sorting through a box of old cassette tapes.',
  'Electro-swing: A con artist attends a fancy party and realizes someone else there is running the exact same scam.',
  'Country-R&B: Two people from wildly different backgrounds discover they grew up hearing the same old songs from their parents.',
  'Hip-hop orchestral storytelling: Follow one apartment building during a citywide power outage, moving room to room between residents.',
  'Acoustic folk: A person records the sounds inside an aging family home before it is sold: doors, pipes, floorboards, appliances, relatives talking from another room.',
  'Dark synth-pop: Someone compulsively checks an ex\'s social media but becomes increasingly bored by what they find instead of devastated.',
  'R&B/rock duet: Two people who have been flirting for months finally hook up and immediately discover they are much better at flirting than communicating.',
  'Genre-bending, soul, hip-hop, rock, gospel and blues: Tell the story of one family gathering through four narrators: the person hosting, the relative nobody trusts, the teenager overhearing everything, and the oldest person in the room who knows the backstory everybody else is arguing about.',
];
