import { rhymeKeyTable, rhymeWordTable } from './rhymeLexicon';

/* Part 320 (Oct 8 2026). The desk could not hear rhyme: its checks were about repeated words and
 * stock phrases, so a verse whose lines rhymed with nothing passed, and so did a song whose every
 * rhyme was a plain one-syllable pair. This reads a word's sound from a table of the ~28,000 most
 * common English words (CMUdict rhyme keys, generated by scratchpad/build_rhyme_lexicon.py) and
 * answers two questions about two words: do they rhyme perfectly (same sounds from the last
 * stressed vowel on), or only in a slant way (same stressed vowel and the same kind of closing
 * sound, or the same closing sounds under a different vowel). An unknown word answers nothing, so a
 * name or an invented word is never counted for or against a song. */

const VOWELS: Set<string> = new Set('AA AE AH AO AW AY EH ER EY IH IY OW OY UH UW'.split(' '));
const MANNER: Record<string, string> = {};
for (const [sounds, kind] of [
  ['M N NG', 'nasal'],
  ['P B T D K G', 'stop'],
  ['F V S Z SH ZH TH DH HH', 'fricative'],
  ['L R', 'liquid'],
  ['CH JH', 'affricate'],
  ['W Y', 'glide'],
] as [string, string][])
  for (const sound of sounds.split(' ')) MANNER[sound] = kind;

/** Words that sound alike and are spelled differently: a pair of them is the same word, not a rhyme. */
const HOMOPHONES: string[][] = [
  ['here', 'hear'],
  ['there', 'their', "they're"],
  ['to', 'too', 'two'],
  ['for', 'four', 'fore'],
  ['hour', 'ours'],
  ['no', 'know'],
  ['night', 'knight'],
  ['write', 'right', 'rite'],
  ['be', 'bee'],
  ['see', 'sea'],
  ['one', 'won'],
  ['sun', 'son'],
  ['wait', 'weight'],
  ['way', 'weigh'],
  ['road', 'rode'],
  ['blue', 'blew'],
  ['eye', 'i', 'aye'],
  ['by', 'buy', 'bye'],
  ['wear', 'where', 'ware'],
  ['tail', 'tale'],
  ['heal', 'heel'],
  ['made', 'maid'],
  ['piece', 'peace'],
  ['whole', 'hole'],
  ['sole', 'soul'],
  ['threw', 'through'],
  ['would', 'wood'],
  ['your', "you're"],
  ['its', "it's"],
];

let keys: string[] | null = null;
let table: Map<string, number> | null = null;

function load(): Map<string, number> {
  if (table) return table;
  keys = rhymeKeyTable.split('|');
  const map = new Map<string, number>();
  for (const entry of rhymeWordTable.split(' ')) {
    const at = entry.lastIndexOf(':');
    if (at > 0) map.set(entry.slice(0, at), parseInt(entry.slice(at + 1), 36));
  }
  table = map;
  return map;
}

/** A word as the table spells it: lower case, straight apostrophes, no outer punctuation. */
export function rhymeWord(word: string): string {
  const w = word
    .toLowerCase()
    .replace(/[’‘`]/g, "'")
    .replace(/^[^a-z']+|[^a-z']+$/g, '');
  if (w === "'cause" || w === "'em") return w;
  return w.replace(/^'+/, '').replace(/(?<!in)'+$/, '');
}

/** The rhyme key of a word (its sounds from the last stressed vowel on, such as "AY.ER"), or
 *  undefined when the word is not in the table. "-in'" is read as "-ing". */
export function rhymeKeyOf(word: string): string | undefined {
  const map = load();
  const w = rhymeWord(word);
  if (!w) return undefined;
  let index = map.get(w);
  if (index === undefined && w.endsWith("in'")) index = map.get(`${w.slice(0, -3)}ing`);
  if (index === undefined && w.endsWith("'s")) index = map.get(w.slice(0, -2));
  return index === undefined || !keys ? undefined : keys[index];
}

/** How many syllables the key spans: "AY.ER" is two, "AA.T" is one. */
export function rhymeSyllables(key: string): number {
  return key.split('.').filter((sound) => VOWELS.has(sound)).length;
}

const homophoneGroup = (word: string): number =>
  HOMOPHONES.findIndex((group) => group.includes(rhymeWord(word)));

/** True when two spellings are one word for rhyming purposes: the same word, or homophones. */
export function sameRhymeWord(a: string, b: string): boolean {
  const x = rhymeWord(a);
  const y = rhymeWord(b);
  if (x === y) return true;
  const g = homophoneGroup(x);
  return g !== -1 && g === homophoneGroup(y);
}

export type RhymeRelation = 'perfect' | 'slant' | null;

/** How two end words rhyme, or null when they do not, when they are the same word, or when either
 *  is unknown. */
export function rhymeRelation(a: string, b: string): RhymeRelation {
  if (sameRhymeWord(a, b)) return null;
  const ka = rhymeKeyOf(a);
  const kb = rhymeKeyOf(b);
  if (!ka || !kb) return null;
  if (ka === kb) return 'perfect';
  const sa = ka.split('.');
  const sb = kb.split('.');
  // The first vowel is the stressed one; what follows it within its syllable is the closing sound.
  const closing = (sounds: string[]): string[] => {
    const out: string[] = [];
    for (const sound of sounds.slice(1)) {
      if (VOWELS.has(sound)) break;
      out.push(sound);
    }
    return out;
  };
  const ca = closing(sa);
  const cb = closing(sb);
  const kindA = ca.length ? MANNER[ca[ca.length - 1]] || 'x' : 'open';
  const kindB = cb.length ? MANNER[cb[cb.length - 1]] || 'x' : 'open';
  if (sa[0] === sb[0] && kindA === kindB && rhymeSyllables(ka) === rhymeSyllables(kb))
    return 'slant';
  if (ca.length && ca.join('.') === cb.join('.') && rhymeSyllables(ka) === rhymeSyllables(kb))
    return 'slant';
  return null;
}

/** Whether a word is known to the table at all. */
export function knowsWord(word: string): boolean {
  return rhymeKeyOf(word) !== undefined;
}
