const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=process.env.REVERIE_RECEIPTS || path.join(__dirname,'receipts');
fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL ? {channel:process.env.PLAYWRIGHT_CHANNEL} : {}),args:['--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1280,height:1000},deviceScaleFactor:1});
 const errors=[],checks=[];
 const check=(value,label)=>{assert(value,label);checks.push(label);};
 page.on('pageerror',e=>errors.push(e.message));
 page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
 await page.addInitScript(()=>{
  window.addEventListener('reverie-stage-ready',()=>{
   const Original=window.ReverieStage.Stage;
   window.ReverieStage.Stage=class extends Original{constructor(...args){super(...args);window.stageForTest=this;}};
  });
 });
 await page.goto('http://127.0.0.1:8169/world');await page.waitForSelector('.has-stage');
 const send=async cmd=>{
  await page.locator('#cmdInput').fill(cmd);await page.locator('#cmdInput').press('Enter');
  await page.waitForFunction(()=>document.getElementById('cmdForm').getAttribute('aria-busy')!=='true');
 };
 await send('go to pats');
 await page.locator('#reverieIllustration').screenshot({path:path.join(out,'diner-final.png')});
 await send('hangout host records');await send('hangout invite Pat');
 check((await page.locator('#hangoutGuests').textContent()).includes('Pat'),'actual engine invitation appears in gathering controls');
 await page.locator('#reverieIllustration').screenshot({path:path.join(out,'record-night.png')});
 check(await page.evaluate(()=>!!window.stageForTest.model.hangout),'gathering changes the actual 3D scene');
 await send('hangout finish');
 await send('go to Reedbank Creek');
 await page.waitForFunction(()=>window.stageForTest.model.type==='creek');
 await page.locator('#reverieIllustration').screenshot({path:path.join(out,'creek-final.png')});
 check(await page.evaluate(()=>document.querySelectorAll('[role=log]').length===1),'one live world log');
 check(await page.evaluate(()=>document.querySelector('canvas').closest('[aria-hidden=true]')!==null),'canvas hidden from assistive technology');
 await page.locator('#cmdInput').fill('my unsent thought');
 await page.evaluate(()=>window.ReverieRoom.people([{id:'fixture-person',name:'Mira Example',kind:'player',line:'Mira Example'}]));
 check(await page.locator('#cmdInput').inputValue()==='my unsent thought','passive picture updates preserve command draft');
 check(await page.locator('#cmdInput').evaluate(el=>el===document.activeElement),'passive picture updates preserve focus');
 await page.locator('#cmdInput').fill('');
 await page.locator('details.settings summary').click();
 await page.locator('#describePicture').click();
 check((await page.locator('#log').innerText()).includes('handcrafted miniature'),'picture description delivered to existing live log');
 await page.locator('#motionToggle').click();
 check(await page.evaluate(()=>window.stageForTest.running===false),'saved motion control stops render loop');
 const savedTime=await page.evaluate(()=>window.stageForTest.time);await page.waitForTimeout(200);
 check(await page.evaluate(()=>window.stageForTest.time)===savedTime,'paused motion does not advance');
 await page.locator('#illustrationToggle').click();
 check(await page.locator('canvas').count()===0,'picture off disposes canvas');
 check(await page.evaluate(()=>window.stageForTest.disposed),'picture off disposes GPU view');
 await page.reload();await page.waitForFunction(()=>document.getElementById('cmdInput').disabled===false);
 check(await page.locator('canvas').count()===0,'picture preference survives reload');
 await page.locator('details.settings summary').click();await page.locator('#illustrationToggle').click();await page.waitForSelector('.has-stage');
 check(await page.evaluate(()=>!window.stageForTest.running),'motion preference survives reload');
 await page.locator('#motionToggle').click();
 await page.emulateMedia({reducedMotion:'reduce'});
 check(await page.evaluate(()=>!window.stageForTest.running),'device reduced motion overrides animated preference');
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.locator('#reverieIllustration').scrollIntoViewIfNeeded();
 await page.waitForFunction(()=>window.stageForTest.running===true);
 await page.locator('footer').scrollIntoViewIfNeeded();await page.waitForFunction(()=>window.stageForTest.running===false);
 check(true,'offscreen picture stops render loop');
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});
 check(await page.evaluate(()=>!window.stageForTest.running),'hidden page stops render loop');
 await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});
 await page.locator('#reverieIllustration').scrollIntoViewIfNeeded();
 await page.locator('.picture-controls summary').click();
 const angle=await page.evaluate(()=>window.stageForTest.angle);await page.locator('#viewRight').click();
 check(await page.evaluate(()=>window.stageForTest.angle)>angle,'camera button rotates picture');
 for(const width of [320,390,667,1040]) {
  await page.setViewportSize({width,height:844});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no horizontal overflow at '+width);
 }
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:path.join(out,'mobile-final.png'),fullPage:true});
 await page.evaluate(()=>window.stageForTest.renderer.forceContextLoss());
 await page.waitForFunction(()=>document.querySelector('canvas')===null);
 check(await page.locator('.reverie-fallback svg').count()===1,'WebGL context loss restores illustration');
 await send('look');check((await page.locator('#s-name').textContent()).includes('Creek'),'game remains usable after WebGL loss');
 const native=await browser.newPage({viewport:{width:390,height:300}});
 await native.goto('http://127.0.0.1:8169/native/ReverieStage.html');
 const fixture={room:{roomId:'alder_camp',name:'Alder Camp',desc:'A tended fire',outdoor:true,sensory:{nature:true},peopleDetail:[{id:'friend',name:'Mira',kind:'player'}]},hud:{name:'Alex',dark:true}};
 const described=await native.evaluate(s=>window.reverieNativeUpdate(s,false),fixture);
 check(described.includes('stone fire ring'),'offline native bundle renders snapshot and describes it');
 await native.locator('canvas').screenshot({path:path.join(out,'native-bundle-camp.png')});
 await native.evaluate(()=>window.reverieNativeDispose());check(await native.locator('canvas').count()===0,'native bundle teardown removes canvas');
 check(errors.length===0,'no page errors or failed HTTP resources');
 fs.writeFileSync(path.join(out,'browser-acceptance.json'),JSON.stringify({checks,errors,fixtures:'Local disposable Mongo world; native bundle uses invented snapshot. Not a physical-phone or live-user test.'},null,2));
 console.log(checks.length+' browser checks passed');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
