const bespoke: Record<string, string[]> = {
  'childhood imagination': [
    'Let us invent a school subject that should exist.',
    'Give me two superpowers and one silly drawback.',
    'What would be the funniest rule for a made-up kingdom?',
    'Let us design a playground for tiny dragons.',
    'Make up a snack with a ridiculous name.',
    'Give me a mystery with a clue I can work out.',
    'What would happen if backpacks could complain?',
    'Give me a quick quiz with one trick question.',
    'Help me turn a boring homework topic into something interesting.',
    'Let us write a story that starts with a very suspicious sandwich.',
    'Pick a harmless debate and let me take a side.',
    'Invent a new sport we could play on the moon.',
    'Give me a challenge where I can only use five words.',
    'What ordinary thing would make the best secret hideout?',
  ],
  cooking: [
    'What dish makes better leftovers than the first meal?',
    'Defend frozen vegetables to somebody who thinks they are beneath them.',
    'If dinner can only use one pan, what are we making?',
    'Which ingredient gets blamed when the problem is really technique?',
    'What kitchen shortcut saves time without ruining the food?',
    'Plan a good dinner around one cheap ingredient.',
    'Settle a food argument: when does texture matter more than flavor?',
    'Which cooking rule do people obey long after it stops helping?',
    'Give me a dish where the ugly version tastes better than the pretty one.',
    'What would you cook for someone convinced they hate vegetables?',
    'Build a sandwich with one ingredient people would argue about.',
    'What makes a very simple soup taste like somebody cared?',
    'Give me a tiny cooking experiment where two methods taste different.',
    'What food opinion would start a friendly argument at a potluck?',
  ],
  music: [
    'Pick a song where the quietest part does the most work.',
    'What musical detail do cheap speakers make people miss?',
    'Choose a cover version that earns the right to exist.',
    'Which song sounds happy until you actually listen to the words?',
    'Build a playlist where each song changes the meaning of the next.',
    'What makes a bass line worth paying attention to?',
    'Defend a musical genre that people dismiss too quickly.',
    'What makes a rough recording better than a polished one?',
    'Pick a song whose first ten seconds tell you exactly what it is.',
    'What album needs to be heard in order instead of shuffled?',
    'Choose a song for a movie scene with no dialogue.',
    'Which musical rule is more interesting when somebody breaks it?',
    'What is an instrument people rarely notice until it disappears?',
    'Give me two songs with the same mood and completely different machinery.',
  ],
  'eerie mysteries': [
    'Give me a haunted-house premise where the house is the reasonable one.',
    'How would you investigate a ghost report without mocking the witness?',
    'Pick a famous mystery where the boring explanation is surprisingly strong.',
    'What separates an eerie coincidence from useful evidence?',
    'Invent a fictional mystery with one clue hiding in a perfectly ordinary sound.',
    'What makes an abandoned place creepy before anybody tells you a story?',
    'Explain how a spooky photograph can fool an honest person.',
    'Give me a ghost story without a jump scare or a tragic little girl.',
    'What would a skeptic and a believer both need to check at a strange house?',
    'Invent a fictional witness who is truthful but has misunderstood one crucial thing.',
    'What kind of missing document could change an unsolved case?',
    'Tell me a folklore idea that becomes stranger when you look at its origins.',
    'What is the creepiest thing a perfectly ordinary object could do in a fictional scene?',
    'Let us design a mystery where the first sensible explanation is almost right.',
  ],
  gardening: [
    'What would you plant in a garden that has to survive occasional neglect?',
    'Make the case for a plant people dismiss as a weed.',
    'Which gardening job is easier at the wrong-looking time?',
    'Design a container garden around one awkward corner.',
    'What is a small change that makes a garden better for wildlife?',
    'How would you tell thirsty soil from a plant with another problem?',
    'What would you grow mostly for the pleasure of watching it?',
    'Give me a gardening experiment that compares two growing conditions.',
    'What plant pairing works for a reason people might miss?',
    'What would make a small garden interesting even when nothing is flowering?',
    'Which plant-care rule causes trouble when people apply it to everything?',
    'Plan a garden around scent instead of appearances.',
    'What does a failed seed tray teach you to check next time?',
    'What garden detail tells you somebody has paid attention?',
  ],
  'the natural world': [
    'What could you learn from staying still outdoors for ten minutes?',
    'Pick a supposedly ugly animal and tell me what makes it remarkable.',
    'What does a patch of untidy ground offer that a neat lawn does not?',
    'Explain a natural sound people usually ignore.',
    'What small sign tells you an animal has been nearby?',
    'Which common bird has a more interesting life than its reputation suggests?',
    'What changes in a familiar place when you visit after dark?',
    'Give me a nature observation I can try without special equipment.',
    'What is an ordinary adaptation that works like a clever invention?',
    'How can two animals share a place without competing for the same thing?',
    'What makes a fallen tree useful long after it dies?',
    'Pick a natural process that is easy to mistake for a disaster.',
    'What can you notice outside with your ears before your eyes?',
    'Tell me how a tiny creature can change a much larger environment.',
  ],
  'digital security': [
    'What would you check first if a login message looked almost legitimate?',
    'Explain why a familiar sender name is not enough to trust a message.',
    'Compare two-factor methods using an ordinary real-world example.',
    'What security measure looks reassuring but does very little?',
    'Help me separate a real security problem from a scary headline.',
    'Explain what a password manager changes besides remembering passwords.',
    'What clue in a suspicious link is easy to overlook?',
    'Give me a fictional phishing message and let me find the tell.',
    'Which privacy tradeoff should people understand before choosing an app?',
    'What is the difference between a software bug and a security weakness?',
    'Help me design a simple account-recovery checklist.',
    'What would you ask before trusting a service with important files?',
    'Explain a common encryption misconception with one concrete example.',
    'What small habit would make an ordinary device less vulnerable?',
  ],
  'contracts and legal questions': [
    'Which tiny words in a contract can change the whole deal?',
    'Show me two fictional contract clauses that sound alike but behave differently.',
    'Help me make a timeline of events for a dispute.',
    'What makes a demand letter firm without making it theatrical?',
    'Help me identify what this agreement says about cancellation.',
    'Translate a fictional clause that hides its meaning in polite language.',
    'Help me compare what a contract promises with what it excludes.',
    'What details should I gather before asking about a disputed charge?',
    'Help me write a factual account without accidentally arguing every sentence.',
    'What would you look for in the fees section of an agreement?',
    'Help me distinguish an obligation from a suggestion in this wording.',
    'Explain why the definition section of a contract can matter so much.',
    'Help me frame a clear question for a qualified local professional.',
    'What can make an apparently simple agreement surprisingly one-sided?',
  ],
  travel: [
    'Design an afternoon around one neighborhood instead of five famous sights.',
    'What makes a local market more interesting than a souvenir shop?',
    'Plan a trip where the journey is part of the point.',
    'Give me two very different ways to spend a rainy travel day.',
    'What would you learn about a place before deciding where to stay?',
    'Help me choose between doing more and enjoying one thing properly.',
    'What ordinary local routine would be worth experiencing as a visitor?',
    'Plan a day with one paid stop and the rest free.',
    'What makes a good travel story besides things going wrong?',
    'Give me a packing decision where less really is easier.',
    'How would you explore a new place through its sounds and food?',
    'What would make a short trip feel less rushed?',
    'Help me find the right question to ask a local instead of asking for hidden gems.',
    'What is a small cultural custom worth understanding before a visit?',
  ],
  'history and family research': [
    'What could a grocery receipt tell a historian about an ordinary day?',
    'Show me how two truthful records can appear to contradict each other.',
    'What would you investigate when a family story has the right names but the wrong date?',
    'Pick a historical change that people first noticed in their kitchens.',
    'What is a useful clue in an old photograph besides the faces?',
    'How would you research an ancestor without assuming the family legend is right?',
    'What everyday job tells you something surprising about a past era?',
    'Give me a historical question a census record cannot answer by itself.',
    'What makes a primary source useful even when its author is biased?',
    'Show me how a small spelling difference can complicate family research.',
    'What ordinary possession would be worth putting in a local museum?',
    'Pick a historical disagreement where the missing evidence matters most.',
    'How can you keep a good family story while being honest about what is uncertain?',
    'What would a historian want to know about a familiar household object?',
  ],
  'coffee and tea': [
    'What hot drink deserves more attention than its fashionable rival?',
    'Build a cafe menu with only three drinks and one excellent snack.',
    'What makes a place comfortable enough for people to stay and talk?',
    'Help me change one thing about how I make a hot drink.',
    'What is a coffee or tea ritual that is worth taking slowly?',
    'Make the case for a cheap mug over a very expensive one.',
    'What snack makes more sense with tea than with coffee?',
    'Give me a tiny taste experiment comparing two brewing methods.',
    'What would you serve someone who dislikes bitter drinks?',
    'What is a small detail that makes a cafe feel welcoming?',
    'Which hot-drink rule gets repeated as if it applies to everybody?',
    'Invent a fictional cafe whose regulars have one wonderfully odd custom.',
    'What would make a very plain afternoon drink feel like a treat?',
    'Give me a harmless argument a tea lover and a coffee lover could both enjoy.',
  ],
};

export function starterAngles(subject: string): string[] {
  return (
    bespoke[subject] ?? [
      `What would someone get wrong about ${subject} after watching a two-minute video?`,
      `Give me a scenario about ${subject} where two sensible people make opposite choices.`,
      `What ordinary detail about ${subject} becomes fascinating when you explain it?`,
      `What well-meant advice about ${subject} would you challenge?`,
      `Create a low-stakes five-minute challenge about ${subject}.`,
      `What question about ${subject} do beginners ask and experts still argue about?`,
      `Show me a case in ${subject} where the shortcut costs more than it saves.`,
      `What would improve ${subject} if people stopped doing it to impress each other?`,
      `Give me a tiny thought experiment about ${subject} with two defensible answers.`,
      `Which familiar rule about ${subject} is useful, and when does it stop helping?`,
      `Explain a puzzling contradiction in ${subject} with a concrete example.`,
      `What small question about ${subject} has a surprisingly complicated answer?`,
      `Make a case for an overlooked approach to ${subject}.`,
      `Give me an example in ${subject} where one small clue changes the whole interpretation.`,
    ]
  );
}
