const assert=require('node:assert/strict');
const mongoose=require('mongoose');const {MongoMemoryServer}=require('mongodb-memory-server');
(async()=>{
 const mongo=await MongoMemoryServer.create();await mongoose.connect(mongo.getUri());
 let n=0;const check=(v,label)=>{assert(v,label);n++;console.log('PASS',label);};
 const {MooChar,MooRoom,MooEvent}=require('../../../../api/models/kadeMoo');
 const engine=require('../../../../api/app/clients/tools/kademoo/engine');
 const life=require('../../../../api/app/clients/tools/kademoo/life');
 const places=require('../../../../api/app/clients/tools/kademoo/life/places');
 const run=command=>life.runCommand({userId:'laundry-test',displayName:'Wash Test',command,isWizard:true,live:true});
 try {
  const ch=await engine.getOrCreateChar('laundry-test','Wash Test');
  await MooChar.updateOne({_id:ch._id},{$set:{roomId:'patch_gully_road','attrs.life':{created:true,needs:{clean:30,fed:80,rested:80,fun:80,company:80},needsAt:Date.now()}}});
  const before=(await MooChar.findById(ch._id)).attrs.coin;
  let r=await run('ne');check(r.room.roomId==='gully_laundry','new door is reachable through actual movement');
  check(r.room.peopleDetail.some(p=>p.id==='npc:nell'),'Nell is seeded in the actual room');
  check(r.room.sensory.ambience==='amb.laundry.quiet','washer ambience belongs to the room');
  check(r.actions.some(a=>a.cmd==='wash clothes'),'laundry action is discoverable');
  const results=await Promise.all([run('wash clothes'),run('wash clothes')]);
  check(results.filter(r=>r.ok).length===1,'concurrent washing grants one result');
  check((await MooChar.findById(ch._id)).attrs.coin===before,'laundry never charges game money');
  check((await MooChar.findById(ch._id)).attrs.life.needs.clean>30,'washing improves comfort');
  await MooChar.updateOne({_id:ch._id},{$set:{'attrs.busyUntil':0,'attrs.life.laundryAt':0}});
  check((await run('fold laundry')).ok,'folding uses the same actual room');
  await MooChar.updateOne({_id:ch._id},{$set:{'attrs.busyUntil':0,'attrs.life.laundryAt':0}});
  check((await run('sort buttons')).ok,'blue tin supports a real shared activity');
  check(!(await run('sort buttons')).ok,'button activity cannot bypass the laundry cooldown');
  r=await run('look');
  check(['repair bench','book exchange','sort buttons'].every(cmd=>r.actions.some(a=>a.cmd===cmd)),'new activities have discoverable phone controls');
  check(r.room.washhouse.benchStage===0 && r.room.desc.includes('0 of 3'),'room reports initial bench condition');
  const helper=await engine.getOrCreateChar('laundry-helper','Second Reader');
  await MooChar.updateOne({_id:helper._id},{$set:{roomId:'gully_laundry','attrs.life':{created:true,needsAt:Date.now()}}});
  const runHelper=command=>life.runCommand({userId:'laundry-helper',displayName:'Second Reader',command,isWizard:true,live:true});
  const repair=await Promise.all([run('repair bench 0'),runHelper('repair bench 0')]);
  check(repair.filter(r=>r.ok).length===1,'two people cannot apply the same shared repair twice');
  check((await MooRoom.findOne({roomId:'gully_laundry'})).props.washhouseBench===1,'shared repair advances exactly one step');
  check(!(await run('repair bench 0')).ok,'stale repair button cannot advance the next step');
  check(!(await run('repair bench 2')).ok,'repairs cannot be skipped');
  check((await runHelper('repair bench 1')).ok,'another person can continue the shared repair');
  check((await run('repair bench 2')).ok,'last repair completes bench');
  r=await runHelper('repair bench');
  check(r.lines.some(x=>x.includes('repaired')) && r.choices.length===0,'completed bench is shared and has no repeat reward');
  check(!(await run('repair bench 3')).ok,'finished bench is not repaired twice');
  check(await MooEvent.countDocuments({roomId:'gully_laundry',text:/window bench/})===3,'one public event per committed repair');
  r=await run('book exchange');check(r.choices.length===3,'book shelf offers three complete stories');
  check(!(await run('read washhouse platform 2')).ok,'ending cannot skip unread parts');
  const reading=await Promise.all([run('read washhouse platform 0'),run('read washhouse platform 0')]);
  check(reading.filter(r=>r.ok).length===1,'duplicate reading request moves bookmark only once');
  check((await run('reopen washhouse platform 0')).ok,'missed response can reopen its page without another advance');
  check(!(await run('reopen washhouse platform 1')).ok,'reopen cannot reveal an unread part');
  r=await run('book exchange');check(r.choices[0].cmd==='read washhouse platform 1','bookmark survives a new command');
  r=await runHelper('book exchange');check(r.choices[0].cmd==='read washhouse platform 0','other character has an independent bookmark');
  check(!(await run('read washhouse platform 0')).ok,'stale reading button cannot skip forward');
  check((await run('read washhouse platform 1')).ok,'second part reads from saved place');
  r=await run('read washhouse platform 2');check(r.ok && r.lines.some(x=>x.startsWith('The end.')),'story has an actual ending');
  r=await run('reopen washhouse platform 2');check(r.ok && r.choices.some(x=>x.cmd==='reopen washhouse platform 1'),'opened pages provide backward navigation');
  check((await run('reread washhouse platform')).ok,'explicit reread resets a finished story');
  for(const command of ['read washhouse bad 0','read washhouse key 99','read washhouse key 0 extra','reread washhouse key','read washhouse __proto__ 0'])
    check(!(await run(command)).ok,'invalid or stale request rejected: '+command);
  for(const id of ['key','page']) for(let page=0;page<3;page++) check((await run(`read washhouse ${id} ${page}`)).ok,'complete readable story '+id+' part '+page);
  r=await runHelper('look');
  check(!JSON.stringify(r.room).includes('washhousePages'),'private bookmarks never enter public room payload');
  check((await MooChar.findById(ch._id)).attrs.coin===before,'all new activities remain free');
  const help=await run('help book exchange');check(help.ok && help.lines.join(' ').includes('books stay on the shelf'),'in-game help explains saved reading and book location');
  await MooChar.updateOne({_id:ch._id},{$set:{'attrs.busyUntil':0}});
  r=await run('sw');check(r.room.roomId==='patch_gully_road','return path leads back to Gully Road');
  check(!(await run('wash clothes')).ok,'wash action requires the actual machines');
  for(const cmd of ['repair bench','book exchange','read washhouse platform 0','sort buttons'])check(!(await run(cmd)).ok,'room required: '+cmd);
  await MooRoom.updateOne({roomId:'patch_gully_road'},{$set:{'exits.ne':'owner-door'}});
  await MooRoom.updateOne({roomId:'gully_laundry'},{$set:{desc:'Owner edited room'}});
  await places.seed();
  check((await MooRoom.findOne({roomId:'patch_gully_road'})).exits.ne==='owner-door','seed never replaces an owner exit');
  check((await MooRoom.findOne({roomId:'gully_laundry'})).desc==='Owner edited room','seed never replaces edited room prose');
  check((await MooRoom.findOne({roomId:'gully_laundry'})).props.washhouseBench===3,'reseed preserves shared repairs');
  check((await MooChar.findById(ch._id)).attrs.life.washhousePages.key===3,'reseed preserves private bookmarks');
  check(await MooChar.countDocuments({userId:'npc:nell'})===1,'population seed creates exactly one Nell');
  console.log(n+' washhouse checks passed');
 }finally{await mongoose.disconnect();await mongo.stop();}
})().catch(e=>{console.error(e);process.exit(1);});
