const assert=require('node:assert/strict');
const mongoose=require('mongoose');
const {MongoMemoryServer}=require('mongodb-memory-server');
const api=require('@librechat/api');
let checks=0;
const check=(value,label)=>{assert(value,label);checks++;console.log('PASS',label);};
(async()=>{
 const mongo=await MongoMemoryServer.create();await mongoose.connect(mongo.getUri());
 const {MooChar,MooRoom,MooDistrict,MooEvent}=require('../../../../api/models/kadeMoo');
 const engine=require('../../../../api/app/clients/tools/kademoo/engine');
 const life=require('../../../../api/app/clients/tools/kademoo/life');
 const planning=require('../../../../api/app/clients/tools/kademoo/life/planning');
 const run=(command,isWizard=true)=>life.runCommand({userId:'pilot-test',displayName:'Pilot Test',command,isWizard,live:true});
 const tick=async()=>{planning.tickResidents(['pats_diner'],'clear');await planning.settled();};
 const original=global.fetch;
 try {
  const ch=await engine.getOrCreateChar('pilot-test','Pilot Test');
  await MooChar.updateOne({_id:ch._id},{$set:{roomId:'pats_diner','attrs.life':{created:true,needsAt:Date.now()},'attrs.privateNote':'never send private-note-sentinel'}});
  await run('look');await planning.settled();
  let requests=0,seen='';
  process.env.REFRAME_PROXY_SECRET='test-placeholder';
  global.fetch=async(url,options)=>{requests++;seen=options.body;return {ok:true,json:async()=>({choices:[{message:{content:'{"actions":["wipe","coffee","stretch"]}'}}]})};};
  await tick();check(requests===0,'no model request before trial is explicitly started');
  check(!(await run('@resident pilot start',false)).ok,'ordinary players cannot activate spending');
  await run('@resident pilot start');
  delete require.cache[require.resolve('../../../../api/app/clients/tools/kademoo/life/planning')];
  const otherWorker=require('../../../../api/app/clients/tools/kademoo/life/planning');
  otherWorker.tickResidents(['pats_diner'],'clear');
  await Promise.all([tick(),tick(),otherWorker.settled()]);
  check(requests===1,'independent worker instances atomically reserve one request');
  const pat=await MooChar.findOne({userId:'npc:pat'}).lean();
  check(pat.attrs.residentPlan.actions[0]==='wipe','valid model choices become a durable resident plan');
  check(!seen.includes('sentinel')&&!seen.includes('Pilot Test'),'model sees neither private data nor player identity');
  check(!seen.includes('relationship')||seen.includes('cannot change'),'payload contains only authored resident context');
  await tick();
  check((await MooEvent.countDocuments({actorUserId:'npc:pat',text:/wipes a small patch/}))===1,'an actual room event describes applied activity');
  await tick();check((await MooEvent.countDocuments({actorUserId:'npc:pat',text:/wipes a small patch/}))===1,'repeated ticks never duplicate a step event');
  let view=await run('look');
  check(view.room.peopleDetail.find(p=>p.id==='npc:pat').tag==='wiping the counter','actual public payload reflects the model-selected action');
  check(!JSON.stringify(view).includes('residentPlan'),'private planner state stays out of public payload');
  await run('hangout host records');
  await MooDistrict.updateOne({districtId:api.RESIDENT_PILOT.id},{$set:{'props.nextAt':0}});
  await MooChar.updateOne({userId:'npc:pat'},{$unset:{'attrs.residentPlan':1}});
  await tick();check(requests===1,'gatherings protect residents from planning');
  await run('hangout finish');
  global.fetch=async()=>{requests++;throw new Error('uncertain transport');};
  await tick();check((await MooDistrict.findOne({districtId:api.RESIDENT_PILOT.id})).props.calls===2,'failed provider keeps its reservation');
  await tick();check(requests===2,'failed provider is not retried on next tick');
  await MooDistrict.updateOne({districtId:api.RESIDENT_PILOT.id},{$set:{'props.nextAt':0,'props.calls':12}});
  await tick();check(requests===2,'hard lifetime ceiling prevents more calls');
  await run('@resident pilot start');check((await MooDistrict.findOne({districtId:api.RESIDENT_PILOT.id})).props.calls===12,'start cannot refill allowance');
  await MooDistrict.updateOne({districtId:api.RESIDENT_PILOT.id},{$set:{'props.calls':0,'props.nextAt':0,'props.enabledUntil':0}});
  await tick();check(requests===2,'expiry or pause prevents more calls');
  await MooDistrict.updateOne({districtId:api.RESIDENT_PILOT.id},{$set:{'props.enabledUntil':Date.now()+60000}});
  await MooChar.updateOne({userId:'pilot-test'},{$set:{lastActiveAt:new Date(0)}});
  await tick();check(requests===2,'NPCs and strays alone cannot trigger paid planning');
  const opts=api.residentOptions('pats_diner',false);
  const fixture={roomId:'pats_diner',schedule:'working the grill',actions:['wipe','coffee'],startedAt:Date.now(),emitted:-1};
  check(api.activeResidentAction(fixture,'elsewhere','working the grill',false)===null,'moving room invalidates a plan');
  check(api.activeResidentAction(fixture,'pats_diner','off duty',false)===null,'changing schedule invalidates a plan');
  check(api.activeResidentAction(fixture,'pats_diner','working the grill',false,fixture.startedAt+999999)===null,'expired plans restore ordinary schedule');
  check(!api.activeResidentAction({...fixture,actions:['give_money']},'pats_diner','working the grill',false),'unknown actions cannot be applied');
  for(const bad of ['null','{"actions":["give_money"]}','{"actions":[]}','{"actions":[1]}','```json\n{}\n```']) {
   global.fetch=async()=>({ok:true,json:async()=>({choices:[{message:{content:bad}}]})});
   check(await api.planResident({name:'Pat',character:'Cook',roomName:'Diner',roomId:'pats_diner',schedule:'working',weather:'clear',previous:[],options:opts})===null,'malformed or unauthorized model output rejected');
  }
  console.log(checks+' planning checks passed');
 } finally {global.fetch=original;delete process.env.REFRAME_PROXY_SECRET;await planning.settled();await mongoose.disconnect();await mongo.stop();}
})().catch(e=>{console.error(e);process.exit(1);});
