const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('../../node_modules/playwright');
const root=path.join(__dirname,'out-voice'),out=process.env.CHARACTER_RECEIPTS || path.join(__dirname,'check-output'); fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://local').pathname);const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.wav':'audio/wav','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(8178,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:360,height:740}});const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
await page.addInitScript(()=>{window.__voiceFrames=0;const original=requestAnimationFrame;window.requestAnimationFrame=callback=>original(t=>{window.__voiceFrames++;callback(t);});});
await page.goto('http://127.0.0.1:8178/');await page.getByRole('button',{name:'Play saved voice',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('canvas') && !document.querySelector('canvas').hidden);
const describe=page.locator('summary').filter({hasText:'Describe character'});
await describe.focus();await page.keyboard.press('Enter');
assert.equal(await page.locator('details').getAttribute('open'),'');
assert.match(await page.locator('details').innerText(),/Kiana is a young Black woman/);
assert.equal(await page.evaluate(()=>window.voiceFixture.audio.paused),false);
await page.waitForTimeout(120);
assert.equal(await page.evaluate(()=>document.activeElement?.tagName),'SUMMARY');
await page.screenshot({path:path.join(out,'web-voice-description.png')});
await page.getByRole('button',{name:'Pause voice message',exact:true}).locator('..').screenshot({path:path.join(out,'web-voice-description-card.png')});
await page.keyboard.press('Enter');
await page.waitForTimeout(700);await page.screenshot({path:path.join(out,'web-voice-speaking.png')});
const before=await page.evaluate(()=>window.voiceFixture.audio.currentTime);
await page.getByRole('button',{name:'Pause voice message',exact:true}).click();await page.getByRole('button',{name:'Resume voice message',exact:true}).waitFor();
await page.waitForTimeout(250);const paused=await page.evaluate(()=>({time:window.voiceFixture.audio.currentTime,paused:window.voiceFixture.audio.paused,hidden:document.querySelector('canvas').hidden}));assert.equal(paused.paused,true);assert.equal(paused.hidden,true);assert.ok(Math.abs(paused.time-before)<.3);
await page.screenshot({path:path.join(out,'web-voice-paused.png')});const count=requests.length;
await page.getByRole('button',{name:'Resume voice message',exact:true}).click();await page.waitForTimeout(200);assert.ok(await page.evaluate(()=>window.voiceFixture.audio.currentTime)>paused.time);assert.equal(requests.length,count);
await page.getByRole('checkbox',{name:'Animated voice portraits'}).uncheck();assert.equal(await page.locator('canvas').count(),0);assert.equal(await page.evaluate(()=>window.voiceFixture.audio.paused),false);
await page.locator('summary').click();assert.match(await page.locator('details').innerText(),/Kiana is a young Black woman/);
assert.equal(await page.locator('img').count(),0);
await page.getByRole('button',{name:'Pause voice message',exact:true}).locator('..').screenshot({path:path.join(out,'web-voice-hidden-description.png')});
await page.locator('summary').click();
await page.getByRole('checkbox',{name:'Animated voice portraits'}).check();await page.getByRole('button',{name:'Play saved voice',exact:true}).click();
await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(150);assert.equal(await page.locator('canvas').evaluate(c=>c.hidden),true);
const stillFrames=await page.evaluate(()=>window.__voiceFrames);await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>window.__voiceFrames),stillFrames);
assert.equal(await page.evaluate(()=>window.voiceFixture.audio.paused),false);
await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForFunction(()=>document.querySelector('canvas') && !document.querySelector('canvas').hidden);
await page.getByRole('button',{name:'Play another character',exact:true}).click();await page.waitForFunction(()=>document.querySelector('img')?.getAttribute('src')==='/test-portrait.svg');assert.equal(await page.locator('canvas').evaluate(c=>c.hidden),true); // generic portraits have no facial rig
assert.equal(await page.locator('summary').count(),0);
assert.equal(await page.locator('img').evaluate(img=>img.parentElement.style.transform),'rotate(0deg) translateY(0px)');
await page.waitForTimeout(100);const genericFrames=await page.evaluate(()=>window.__voiceFrames);await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>window.__voiceFrames),genericFrames);
await page.screenshot({path:path.join(out,'web-voice-other-character.png')});
await page.getByRole('button',{name:'Interrupt',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('canvas').length===0);
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.setViewportSize({width:320,height:640});await page.getByRole('button',{name:'Play Della',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('canvas') && !document.querySelector('canvas').hidden);
await page.locator('summary').click();assert.match(await page.locator('details').innerText(),/Della is an older Black woman/);
await page.evaluate(()=>document.documentElement.style.fontSize='200%');
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('details').scrollIntoViewIfNeeded();
await page.screenshot({path:path.join(out,'web-voice-large-text.png')});
await page.getByRole('button',{name:'Pause voice message',exact:true}).locator('..').screenshot({path:path.join(out,'web-voice-large-text-card.png')});
await page.evaluate(()=>document.documentElement.style.fontSize='');
await page.getByRole('button',{name:'Pause voice message',exact:true}).click();
await page.evaluate(()=>{const audio=window.voiceFixture.audio;window.voiceFixture.originalPlay=audio.play;audio.play=()=>Promise.reject(new Error('Synthetic playback denial'));});
await page.getByRole('button',{name:'Resume voice message',exact:true}).click();
await page.getByRole('status').filter({hasText:'Playback could not resume'}).waitFor();
assert.equal(await page.evaluate(()=>window.voiceFixture.audio.paused),true);
await page.evaluate(()=>{const fixture=window.voiceFixture;fixture.audio.play=fixture.originalPlay;});
await page.getByRole('button',{name:'Resume voice message',exact:true}).click();
await page.getByRole('button',{name:'Pause voice message',exact:true}).waitFor();
assert.equal(await page.getByRole('status').count(),0);
await page.setViewportSize({width:1040,height:800});await page.getByRole('button',{name:'Play saved voice',exact:true}).click();await page.waitForFunction(()=>document.querySelector('canvas') && !document.querySelector('canvas').hidden);await page.screenshot({path:path.join(out,'web-voice-desktop.png')});
const tree=await page.locator('main').ariaSnapshot();assert.ok(!tree.includes('img'));assert.ok(tree.includes('Pause voice message'));assert.equal(errors.length,0);assert.ok(requests.every(u=>u.startsWith('http://127.0.0.1:8178/')||u.startsWith('blob:')));
await page.evaluate(()=>document.documentElement.classList.add('dark'));
await page.getByRole('button',{name:'Pause voice message',exact:true}).locator('..').screenshot({path:path.join(out,'web-voice-dark-card.png')});
await page.locator('main').evaluate(main=>{main.style.marginTop='2000px';window.scrollTo(0,0);});
await page.waitForTimeout(180);const hiddenFrames=await page.evaluate(()=>window.__voiceFrames);
await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>window.__voiceFrames),hiddenFrames);
assert.equal(await page.evaluate(()=>window.voiceFixture.audio.paused),false);
await page.locator('main').evaluate(main=>main.style.marginTop='');
await page.waitForFunction(()=>!document.querySelector('canvas').hidden);
await page.locator('img').dispatchEvent('error');await page.waitForFunction(()=>document.querySelectorAll('canvas').length===0);await page.waitForTimeout(200);const frames=await page.evaluate(()=>window.__voiceFrames);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.__voiceFrames),frames);assert.equal(await page.evaluate(()=>window.voiceFixture.audio.paused),false);
const missing=await browser.newPage({viewport:{width:360,height:740}});
await missing.addInitScript(()=>{window.__voiceFrames=0;const original=requestAnimationFrame;window.requestAnimationFrame=callback=>original(t=>{window.__voiceFrames++;callback(t);});});
await missing.route('**/assets/characters/kiana/*.webp',route=>route.abort());
await missing.goto('http://127.0.0.1:8178/');await missing.getByRole('button',{name:'Play saved voice',exact:true}).click();
await missing.getByRole('button',{name:'Pause voice message',exact:true}).waitFor();await missing.waitForTimeout(350);
const failedFrames=await missing.evaluate(()=>window.__voiceFrames);await missing.waitForTimeout(180);
assert.equal(await missing.evaluate(()=>window.__voiceFrames),failedFrames);
assert.equal(await missing.locator('canvas').evaluate(canvas=>canvas.hidden),true);
assert.equal(await missing.evaluate(()=>window.voiceFixture.audio.paused),false);
await missing.locator('summary').click();assert.match(await missing.locator('details').innerText(),/Kiana is a young Black woman/);
fs.writeFileSync(path.join(out,'voice-browser.json'),JSON.stringify({passed:true,failedImageStopsFrames:true,missingRigKeepsStillPortrait:true,offscreenStopsFrames:true,hiddenAppearanceAvailable:true,largeText320:true,paused,noNewRequestsOnResume:true,errors,requests,tree},null,2));await browser.close();server.close();console.log('Voice-message browser checks pass: playback, pause/resume without requests, reduced/off, identity, interrupt, layouts, accessibility and image-failure cleanup.');
})().catch(e=>{console.error(e);server.close();process.exit(1)});
