/**
 * Party decks for the judge-card games (July 4 2026 overnight build).
 *
 * WILD BLANKS — our fill-in-the-blank party game (the Cards-Against-style
 * one Kade asked for, 100% original cards). Two pools:
 *   MILD  — family table. Kids' accounts ONLY ever see this pool.
 *   SPICY — the adult table (weed, drinking, innuendo, midlife despair).
 *           House lines: no slurs, no hate, nothing graphic — the funny is
 *           absurdity, not shock. Adults get MILD+SPICY shuffled together.
 *
 * CRAB APPLES — our Apples-to-Apples-style comparison game. Judge flips a
 * GREEN description card, everyone plays the RED thing card that fits (or
 * hilariously doesn't). All clean, heavy on Ozarks flavor.
 *
 * Kade-AI in-jokes are sprinkled in on purpose — the family plays these
 * games with Deuce dealing and the sound pack popping off, so the decks
 * know where they live.
 */

const BLANK_PROMPTS_MILD = [
  'Grandma keeps ____ in her purse at all times.',
  "The school talent show was cancelled after somebody's ____ got loose.",
  'The secret ingredient in the church potluck casserole is ____.',
  'My dog has been staring at ____ for three hours.',
  "The tooth fairy has started leaving ____ instead of money.",
  'The field trip went sideways the second the bus driver saw ____.',
  "This year's county fair blue ribbon goes to ____.",
  'I know it was a weird dream because ____ was there.',
  'The new superhero’s only power is ____.',
  'Step one of my morning routine: ____.',
  'The babysitter quit after finding ____ in the microwave.',
  'Nothing ruins a road trip faster than ____.',
  "The weatherman says there's a 90 percent chance of ____.",
  'My imaginary friend is scared of ____.',
  'The last thing I yelled before the pool closed forever: "____!"',
  'Santa checked his list twice because of ____.',
  'The museum’s newest exhibit is just ____ behind glass.',
  'I trained my goldfish to fetch ____.',
  'The mystery smell in the minivan turned out to be ____.',
  'Every good campfire story ends with ____.',
  'The vending machine at school now sells ____.',
  'My great-great-grandpappy crossed the country with nothing but ____.',
  'The wifi went out and the whole family had to survive on ____.',
  'The petting zoo added ____ and immediately regretted it.',
  'The birthday clown showed up with ____ instead of balloons.',
  'You can tell it’s a fancy restaurant when the menu has ____.',
  'The sequel to my favorite movie is just two hours of ____.',
  'The time capsule from 1985 contained ____ and a sincere apology.',
  'My alarm clock now wakes me up with the sound of ____.',
  'The scarecrow stopped working when the crows discovered ____.',
  'The neighbors put ____ on their lawn and now it’s a whole thing.',
  'The instruction manual was just one page: "Do not touch ____."',
  'The spelling bee ended in chaos when the final word was ____.',
  'Somehow ____ won the science fair.',
  'The pirate’s treasure chest was full of ____.',
  'My favorite lullaby is mostly about ____.',
  'The five-second rule does not apply to ____.',
  'The town raised the tornado siren budget because of ____.',
  'The library’s most overdue book is "The Care and Feeding of ____."',
  'Breakfast of champions: ____.',
];

const BLANK_PROMPTS_SPICY = [
  'The bachelorette party was going fine until ____ showed up.',
  'My therapist says my problems all trace back to ____.',
  'The real reason I got kicked out of the family group chat: ____.',
  "Nothing sobers you up faster than ____.",
  'My love language is ____.',
  'The dispensary’s new loyalty reward is ____.',
  'I knew the date was over when they ordered ____.',
  'The preacher never mentioned ____ again after that Sunday.',
  'My last two brain cells are fighting over ____.',
  'The HOA sent a strongly worded letter about ____.',
  'What really happened at the class reunion: ____.',
  'My toxic trait is ____.',
  "The hangover cure nobody asks for: ____.",
  'The tattoo I regret most is ____ on my lower back.',
  'The neighbors called the cops about ____ again.',
  'My search history is 90 percent ____.',
  'The wedding DJ was fired mid-reception for playing ____.',
  'Forget flowers — nothing says romance like ____.',
  'The gas station bathroom had a vending machine for ____.',
  'I put ____ on my dating profile and the matches got WEIRD.',
  'The family reunion needs a designated referee because of ____.',
  'My New Year’s resolution lasted four hours because of ____.',
  'The secret menu at the waffle place includes ____.',
  'You know it’s a good party when somebody loses ____.',
  'The group chat has seen things, mainly ____.',
  'My guardian angel filed for overtime after ____.',
  'The honeymoon suite came with complimentary ____.',
  'Half my paycheck goes to rent, the other half to ____.',
  'The bouncer took one look at ____ and said absolutely not.',
  'My villain origin story begins with ____.',
  'The potluck got weird when Aunt Rhonda brought ____.',
  'They don’t make a greeting card for ____, and honestly they should.',
  'The safe word is ____.',
  'The county fair banned me over ____ and one misunderstanding.',
  'I would walk 500 miles, but not for ____.',
  'Adulthood is mostly googling ____.',
];

const BLANK_RESPONSES_MILD = [
  'a raccoon with a to-do list',
  'forty pounds of expired glitter',
  'grandpa’s dentures, mid-sentence',
  'an emotionally unavailable goldfish',
  'the world’s loudest kazoo',
  'a pontoon boat with no reverse',
  'seventeen geese in a trench coat',
  'the smell of the school gym',
  'a tractor with heated seats',
  'an entire rotisserie chicken, no plate',
  'the neighbor’s passive-aggressive wind chimes',
  'a possum playing dead for attention',
  'gas station sushi',
  'a bounce house with a slow leak',
  'the last biscuit at the family reunion',
  'a mullet with its own zip code',
  'deer season',
  'a garden gnome witness-protection program',
  'the church bake sale mafia',
  'homemade fireworks',
  'a very confident chihuahua',
  'my cousin’s conspiracy corkboard',
  'a casserole nobody claims',
  'the ice cream truck song at 2 AM',
  'off-brand ketchup',
  'a trampoline in a thunderstorm',
  'the junk drawer',
  'a fanny pack full of bees',
  'karaoke night at the nursing home',
  'my uncle’s "famous" chili',
  'a self-checkout machine with attitude',
  'the mystery meat from the cafeteria',
  'a llama with trust issues',
  'sweet tea strong enough to stand a spoon in',
  'the gravel road to nowhere',
  'a haunted porta-potty',
  'clip-on toenails',
  'the world’s itchiest sweater',
  'a duck that knows too much',
  'my sock puppet lawyer',
  'the Branson bus tour',
  'a lifetime supply of mayonnaise',
  'the neighbor kid’s drum set',
  'an aggressively friendly golden retriever',
  'the bottom of the toy box',
  'a catfish the size of a canoe',
  'glow-in-the-dark dentures',
  'the county fair funnel cake line',
  'a rooster with a nemesis',
  'my imaginary friend’s imaginary friend',
  'a whoopee cushion symphony',
  'the shopping cart with the wobbly wheel',
  'grandma’s "everything" drawer',
  'a scarecrow with a gym membership',
  'the dollar store perfume aisle',
  'a turtle in a hurry',
  'my collection of almost-empty shampoo bottles',
  'the wasp nest by the mailbox',
  'a very polite tornado',
  'crocs with socks',
  'the leftover tangle of Christmas lights',
  'an owl with student loans',
  'the pool noodle graveyard',
  'my little brother’s "potion"',
  'a firefly with a flashlight',
  'the squeaky pew in the third row',
  'an all-you-can-eat pickle bar',
  'the emergency snacks under grandma’s bed',
  'a coyote howling the alphabet',
  'my "world’s okayest fisher" trophy',
  'a corn maze with no exit',
  'the flip phone that will not die',
  'a beaver with a business plan',
  'the giant ball of twine two counties over',
  'an armadillo crossing guard',
  'the mosquito that got away',
  'a lawnmower race gone wrong',
  'the tooth I lost in an apple in 2014',
  'a bullfrog with opinions',
  'the "check engine" light of destiny',
  'a pie-eating contest tie-breaker',
  'the good scissors nobody’s allowed to touch',
  'a goat on the roof again',
  'the neighbor’s prize-winning zucchini',
  'a bat in the sunday school room',
  'the world’s slowest ceiling fan',
  'my rock collection (they’re all the same rock)',
  'a snapping turtle named Kevin',
  'the last firework that never went off',
  'an entire marching band in the kitchen',
  'the smell of rain on gravel',
  'a raccoon holding the flashlight steady',
  'my grandpa’s war with the squirrels',
  'the creek that "ain’t deep"',
  'a barn cat with a payroll',
  'the yard sale painting that watches you',
  'an air horn at a golf game',
  'the deer that owns the backyard now',
  'a fish fry that changed everything',
  'my "lucky" fishing hat',
  'the trampoline the wind took',
  'a very serious pillow fort',
  'the gas station with the good pizza',
  'a peacock with a grudge',
  'the world’s longest yard sale',
  'my collection of hotel soaps',
  'a tumbleweed with somewhere to be',
  'the potato that looks like Elvis',
  'a spelling bee heckler',
  'the flyswatter of judgment',
  'an entire season of mosquito bites',
  'the "gently used" bounce house',
  'a garden hose with a vendetta',
  'the family recipe nobody can read',
  'a June bug in the church fan',
  'the sound the screen door makes',
  'a crawdad boil intervention',
  'the good china we never use',
  'a hay bale rolling toward destiny',
  'the porch light moth convention',
];

const BLANK_RESPONSES_SPICY = [
  'a gas station energy pill called "Donkey Thunder"',
  'my ex’s new boat, "The Alimony"',
  'a bathtub full of boxed wine',
  'the walk of shame past the church van',
  'an edible that hit during the eulogy',
  'my "just one beer" math',
  'a bra full of casino chips',
  'the pastor’s secret vape pen',
  'day-drinking with the in-laws',
  'a prenup written on a napkin',
  'the devil’s lettuce, allegedly',
  'my FBI agent’s browser-history therapy fund',
  'a jello shot older than the marriage',
  'truck nuts on a minivan',
  'the strip club buffet',
  'a love letter to the weed man',
  'my credit score doing a backflip off a bridge',
  'an OnlyFans for feet pics of gas station boots',
  'the "we need to talk" text at 1:58 AM',
  'a hickey at a parent-teacher conference',
  'grandma’s "special" brownies, mislabeled',
  'the last cigarette before quitting, part twelve',
  'a beer koozie at a baptism',
  'my body count of houseplants',
  'the honky-tonk bathroom confessional',
  'a margarita machine with a restraining order',
  'shotgunning a La Croix to fit in',
  'the neighbor’s 4:20 lawn care schedule',
  'a divorce cake, professionally decorated',
  'my "retirement plan" (scratch-offs)',
  'the bail money envelope labeled "vacation"',
  'a romantic evening interrupted by the scanner app',
  'whiskey-aisle eye contact',
  'the DD who ditched us for a raccoon',
  'a motel called the "Dew Drop Inn"',
  'my sponsor’s disappointed voicemail',
  'a thong on the clothesline during the church drive-by',
  'the group chat screenshot that ended two marriages',
  'a beer pong dynasty and nothing else to show for it',
  'my "one that got away" (a cop, literally)',
  'the pregame that outlived the party',
  'a lap dance gift certificate, regifted',
  'the karaoke rendition that got us banned',
  'my situationship’s situationship',
  'a hot tub with a mysterious past',
  'the "brownie points" I traded for actual brownies',
  'a bachelor party pontoon with one life jacket',
  'the wine mom starter pack',
  'a joint venture (it was just a joint)',
  'my last shred of dignity, on layaway',
  'the pull-out method (of the driveway, at 3 AM)',
  'a tinder date at the bait shop',
  'the hangover that filed for disability',
  'a "massage gun" nobody uses on their back',
  'the open bar’s closing argument',
  'a rebound named after a truck',
  'my horoscope enabling me again',
  'the skinny-dipping incident at the church retreat',
  'a burlesque show at the grange hall',
  'the flask disguised as a bible',
  'my "roommate" of eleven years',
  'a stag night that ended in a petting zoo',
  'the twerk heard round the cul-de-sac',
  'a sugar daddy who only pays in venison',
  'the "herbal remedy" guy at the farmers market',
  'my liver’s two weeks notice',
  'a honeymoon fund jar at a divorce party',
  'the panty raid retirement tour',
  'a nudist colony newsletter subscription',
  'my "gym membership" (one visit, January 3rd)',
  'the beer run that crossed state lines',
  'a strip poker game with grandma’s bridge club',
  'the aphrodisiac aisle at the truck stop',
  'my weed guy’s customer loyalty punch card',
  'a moonshine tasting flight',
  'the "adults only" section of the video store, RIP',
  'a booty call from the landline',
  'my last name, her last nerve',
  'the shots we swore we’d never speak of',
  'a cougar den (the bar, not the cave)',
  'the mechanical bull’s no-fly list',
  'a dry county with a wet basement',
  'my "vitamin" gummies in the fancy jar',
  'the neighbor’s midnight hot-tub jazz',
  'a walk of shame with a to-go plate',
  'the bartender who knows too much',
  'a fireball nip in the choir robe',
  'my emotional support whiskey',
  'the vegas trip that stays in the group chat',
  'a keg stand at the gender reveal',
  'the "farmers only" date that brought a chaperone goat',
  'my third nipple’s LinkedIn profile',
  'a pole barn with an actual pole',
  'the wine tasting that became a wine chugging',
  'a beer belly six years in the making',
  'the lingerie football league tryouts',
  'my "quit smoking" gum habit',
  'a skinny margarita with a fat secret',
  'the after-hours bingo underworld',
  'a corn silo speakeasy',
  'my "allergies" every morning after',
  'the church softball trash-talk incident',
  'a dating app for tractors ("FarmersOnly, but worse")',
  'the beer league championship ring pawned twice',
  'my midlife crisis, sponsored by Buc-ee’s',
  'a shotski at the retirement home',
  'the neighbor’s "glamping" divorce phase',
  'an ill-timed reply-all to the whole church',
];

const APPLES_GREEN = [
  'Squeaky', 'Suspicious', 'Majestic', 'Sticky', 'Overpriced', 'Haunted',
  'Delicate', 'Explosive', 'Cozy', 'Slippery', 'Dramatic', 'Crunchy',
  'Invisible', 'Legendary', 'Soggy', 'Feral', 'Fancy', 'Backfiring',
  'Wholesome', 'Chaotic', 'Rusty', 'Glorious', 'Questionable', 'Bouncy',
  'Ancient', 'Sassy', 'Waterproof', 'Forbidden', 'Musical', 'Greasy',
  'Heroic', 'Wobbly', 'Radioactive', 'Polite', 'Unstoppable', 'Fragrant',
  'Sneaky', 'Enormous', 'Disappointing', 'Magical', 'Prickly', 'Humble',
  'Deafening', 'Refreshing', 'Cursed', 'Dependable', 'Slimy', 'Priceless',
  'Ticklish', 'Stubborn', 'Luxurious', 'Loud', 'Microscopic', 'Spicy',
  'Immortal', 'Clumsy',
];

const APPLES_RED = [
  'a screen door in a tornado', 'grandma’s hugs', 'the DMV line',
  'a catfish noodling championship', 'bigfoot', 'the church organ',
  'a brand-new lawnmower', 'dial-up internet', 'a fresh haircut',
  'the Ozarks in October', 'a possum family under the porch', 'homemade jam',
  'a rooster at 5 AM', 'the middle seat', 'a garage sale accordion',
  'hand-me-down cowboy boots', 'the first day of deer season', 'a pool party',
  'my cousin’s garage band', 'a fireworks stand', 'the good parking spot',
  'a pontoon boat', 'biscuits and gravy', 'the county fair ferris wheel',
  'a junk drawer', 'duct tape', 'the last slice of pizza', 'a porch swing',
  'jury duty', 'a bass boat named "Reel Trouble"', 'the school pickup line',
  'a thunderstorm at midnight', 'wet socks', 'a surprise quiz',
  'the neighbor’s wifi password', 'a bake sale', 'morning breath',
  'a tire swing', 'the emergency broadcast test', 'homemade ice cream',
  'a four-wheeler with no brakes', 'the Sunday paper', 'a barn owl',
  'lake hair', 'a gravel driveway', 'the tooth fairy’s budget cuts',
  'a hay ride', 'gas station coffee', 'the world’s largest rocking chair',
  'a garden full of tomatoes', 'bug spray that doesn’t work', 'a pop quiz',
  'the ice cream truck', 'a deer in the headlights', 'grandpa’s stories',
  'a creek full of crawdads', 'the last day of school', 'a broken umbrella',
  'fresh-cut grass', 'a yard full of dandelions', 'the christmas eve service',
  'a mosquito in the bedroom', 'hot pavement in July', 'a snow day',
  'the family photo album', 'a stray cat that chose us', 'cold fried chicken',
  'a two-hour sermon', 'the swimming hole', 'a brand-new box of crayons',
  'road construction season', 'a tackle box', 'the neighbor’s peacock',
  'a quilt from great-grandma', 'the smell of a campfire', 'a full moon',
  'daylight saving time', 'a corn dog', 'the fair’s goldfish prize',
  'a clothesline in the wind', 'frog legs', 'the piano recital',
  'a treehouse with a password', 'buttered corn on the cob', 'a dirt road',
  'the little league championship', 'a wasp at the picnic', 'sunday naps',
  'a parade throwing candy', 'the old truck that always starts', 'sparklers',
  'a spelling bee trophy', 'the water tower', 'a coon dog named Banjo',
  'muddy boots by the door', 'a mason jar of lightning bugs', 'leftover pie',
  'the front pew', 'a fish story that grows every year', 'homemade root beer',
  'a storm cellar', 'the last firefly of summer', 'a bobber going under',
  'the church potluck dessert table', 'a new pocket knife', 'first frost',
  'a tent with one missing pole', 'the drive-in movie', 'canned peaches',
  'a barn dance', 'the paper route', 'a lucky rabbit’s foot',
  'the shade tree', 'a wheelbarrow race', 'popcorn ceilings',
  'a rope swing over the creek', 'the tackle shop bulletin board', 'mud pies',
  'a harmonica on the porch', 'the old mill', 'a double rainbow',
  'the goat that opens gates', 'a crockpot of something', 'skipping stones',
  'the 4-H club', 'a scenic overlook', 'peach cobbler', 'a hound dog’s ears',
  'the town square gazebo', 'a hand-crank ice cream maker', 'dew on the grass',
  'the feed store cat', 'a hollow log', 'fireflies in a jar', 'hot chocolate',
  'a tin roof in the rain', 'the county line', 'a hummingbird feeder',
  'the smell of tomato vines', 'an old barn quilt', 'creek gravel',
  'a well-worn bible', 'the bait shop minnow tank', 'windows down in May',
  'a rocking chair that squeaks', 'the flag on the porch', 'sweet corn season',
  'a dog riding shotgun', 'the courthouse clock', 'a jar of buttons',
  'the smell of diesel and hay', 'a summer storm rolling in', 'quilting circle gossip',
];

module.exports = {
  BLANK_PROMPTS_MILD,
  BLANK_PROMPTS_SPICY,
  BLANK_RESPONSES_MILD,
  BLANK_RESPONSES_SPICY,
  APPLES_GREEN,
  APPLES_RED,
};
